import '../assets/vendor/bootstrap/js/bootstrap.bundle.min.js';
import '../assets/vendor/php-email-form/validate.js';
import '../assets/vendor/aos/aos.js';
import '../assets/vendor/glightbox/js/glightbox.min.js';
import '../assets/vendor/swiper/swiper-bundle.min.js';
import '../assets/vendor/waypoints/noframework.waypoints.js';
import '../assets/vendor/imagesloaded/imagesloaded.pkgd.min.js';
import '../assets/vendor/isotope-layout/isotope.pkgd.min.js';
import '../assets/js/main.js';
